<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<div id="wrapper"><div class="content">
<div class="row"><div class="col-md-12"><div class="panel_s"><div class="panel-body">
<div class="row"><div class="col-md-7"><h4 class="no-margin"><i class="fa fa-stethoscope"></i> <?php echo _l('connect_api_chat_diagnostics'); ?></h4></div><div class="col-md-5 text-right"><a class="btn btn-default" href="<?php echo admin_url('connect_api_chat/settings'); ?>"><i class="fa fa-cog"></i> <?php echo _l('connect_api_chat_open_settings'); ?></a> <a class="btn btn-default" href="<?php echo admin_url('connect_api_chat'); ?>"><i class="fa fa-comments"></i> Chat</a></div></div>
<hr class="hr-panel-heading" />
<?php if(!$debug_enabled){ ?><div class="alert alert-warning"><?php echo _l('connect_api_chat_debug_disabled'); ?></div><?php } ?>
<div class="row"><div class="col-md-6"><h4><?php echo _l('connect_api_chat_diagnostic_checks'); ?></h4><table class="table table-striped"><tbody><?php foreach($checks as $c){ ?><tr><td style="width:36px"><span class="label label-<?php echo $c['ok']?'success':'danger'; ?>"><?php echo $c['ok']?'OK':'ERRO'; ?></span></td><td><strong><?php echo html_escape($c['name']); ?></strong><br><span class="text-muted"><?php echo html_escape($c['detail']); ?></span></td></tr><?php } ?></tbody></table></div>
<div class="col-md-6"><h4>Endpoints</h4><label>Webhook</label><div class="input-group"><input readonly class="form-control" value="<?php echo html_escape($webhook_url); ?>"><span class="input-group-btn"><a target="_blank" class="btn btn-default" href="<?php echo html_escape($webhook_url); ?>"><i class="fa fa-external-link"></i></a></span></div><label class="mtop15">PWA</label><div class="input-group"><input readonly class="form-control" value="<?php echo html_escape($pwa_url); ?>"><span class="input-group-btn"><a target="_blank" class="btn btn-default" href="<?php echo html_escape($pwa_url); ?>"><i class="fa fa-external-link"></i></a></span></div></div></div>
<hr>
<div class="row"><div class="col-md-8"><h4><?php echo _l('connect_api_chat_diagnostic_logs'); ?></h4></div><div class="col-md-4 text-right"><a class="btn btn-default btn-sm" href="<?php echo admin_url('connect_api_chat/download_diagnostics'); ?>"><i class="fa fa-download"></i> <?php echo _l('connect_api_chat_download_diagnostics'); ?></a> <?php echo form_open(admin_url('connect_api_chat/clear_debug_logs'),['style'=>'display:inline']); ?><button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('Limpar todos os logs de desenvolvimento?')"><i class="fa fa-trash"></i> <?php echo _l('connect_api_chat_debug_clear'); ?></button><?php echo form_close(); ?></div></div>
<div class="table-responsive"><table class="table table-bordered table-hover"><thead><tr><th>Data</th><th><?php echo _l('connect_api_chat_debug_level'); ?></th><th><?php echo _l('connect_api_chat_debug_source'); ?></th><th><?php echo _l('connect_api_chat_debug_message'); ?></th><th><?php echo _l('connect_api_chat_debug_status'); ?></th><th><?php echo _l('connect_api_chat_debug_duration'); ?></th><th><?php echo _l('connect_api_chat_debug_context'); ?></th></tr></thead><tbody><?php if(!$logs){ ?><tr><td colspan="7" class="text-center text-muted"><?php echo _l('connect_api_chat_no_debug_logs'); ?></td></tr><?php } foreach($logs as $l){ ?><tr><td style="white-space:nowrap"><?php echo html_escape($l['created_at']); ?></td><td><span class="label label-<?php echo $l['level']==='ERROR'?'danger':($l['level']==='WARNING'?'warning':($l['level']==='DEBUG'?'default':'info')); ?>"><?php echo html_escape($l['level']); ?></span></td><td><?php echo html_escape($l['source']); ?></td><td><?php echo html_escape($l['message']); ?></td><td><?php echo $l['http_status']!==null?(int)$l['http_status']:'-'; ?></td><td><?php echo $l['duration_ms']!==null?(int)$l['duration_ms'].' ms':'-'; ?></td><td><details><summary>ver</summary><pre style="max-width:600px;white-space:pre-wrap;word-break:break-word"><?php echo html_escape($l['context_json']?:'{}'); ?></pre></details></td></tr><?php } ?></tbody></table></div>
</div></div></div></div>
</div></div>
<?php init_tail(); ?>
